### ISSUE TITLE
Dataset download failed.

### ISSUE THREAD

**Issue by zwithz** [DK-Jang/motion_puzzle#2]
Hi~

Thank you for the great and awesome work! This paper is really the first work showing us the posibility of controlling the style of the body parts.

I found that this repo released the code recently, but I encountered a problem that I could not download the dataset successfully. I downloaded it several times but always failed when it was close to 100%. Could you move the dataset to Google Drive or split it to several pieces?

<img width="741" alt="image" src="https://user-images.githubusercontent.com/20885843/187329919-c5f29668-97e1-40d3-aec5-81697db36194.png">

Thanks,
Zack

**Comment by DK-Jang** [comment]
Hello, thank you for interest!
I think dataset file is too large to download at once. I tried several times before, sometimes failed.
I recommend using bash command 
`bash download.sh datasets`
then you can download the dataset successfully.

**Comment by zwithz** [comment]
Actually I did try the bash command, the download failed many times, but I just downloaded it successfully.
Thanks anyway~

**Comment by vicentowang** [comment]
> Actually I did try the bash command, the download failed many times, but I just downloaded it successfully. Thanks anyway~

would you share me with the dataset zip source file ?
